---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kumku-landing-config
data:
  NAME: "vite"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumku-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kumku-landing
  template:
    metadata:
      labels:
        name: kumku-landing
    spec:
      containers:
        - name: kumku-landing
          image: $IMAGE_NAME:$IMAGE_VERSION
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3001
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          envFrom:
            - configMapRef:
                name: kumku-landing-config
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: kumku-landing
      nodeSelector:
        workload-type: $APP_LABEL
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: kumku-landing-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 120
    timeoutSec: 60
    healthyThreshold: 2
    unhealthyThreshold: 3
    port: 3000
    type: HTTP
    requestPath: /

---
# service 
apiVersion: v1
kind: Service
metadata:
  name: kumku-landing
  annotations:
    beta.cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"default": "kumku-landing-backendconfig"}'
spec:
  type: NodePort
  selector:
    name: kumku-landing
  ports:
    - port: 3001
      targetPort: 3001
